[project]
name = "mini-agent"
version = "0.15.1"
description = "A minimal agent."
readme = "README.md"
requires-python = ">=3.14"
authors = [{ name = "Kowyo", email = "kowyo@outlook.com" }]
dependencies = [
    "anthropic>=0.96.0",
    "pillow>=12.2.0",
    "prompt-toolkit>=3.0.52",
    "pyobjc-framework-cocoa>=12.1 ; sys_platform == 'darwin'",
    "python-dotenv>=1.2.2",
    "pyyaml>=6.0.3",
    "rich>=15.0.0",
    "tomli-w>=1.2.0",
]

[dependency-groups]
dev = [
    "prek>=0.3.9",
    "ruff>=0.15.11",
    "ty>=0.0.32",
]

[project.scripts]
mini = "mini_agent:main"

[tool.ruff.lint]
select = ["E", "F", "W", "I", "N", "UP", "B", "C4", "PTH", "ANN", "SIM"]
ignore = ["E501"]

[tool.setuptools.packages.find]
where = ["src"]

[build-system]
requires = ["setuptools>=82.0.1", "mypy[mypyc]>=2.1.0"]
build-backend = "setuptools.build_meta"
